# DAITA - Windows uninstaller
# Reverses _install.ps1: stops DAITA, removes the generated launchers, the
# desktop shortcut, and (optionally) the bundled DAITA-core skills. Leaves your
# data and the DAITA folder itself in place - deleting the folder is the last,
# fully-reversible step you do by hand.
$ErrorActionPreference = "Stop"
$root = Split-Path -Parent $PSScriptRoot

# Flags (all optional; default run is interactive + conservative):
#   -RemoveSkills   also remove the bundled DAITA-core skills it installed
#   -RemoveEnv      also delete .env (your saved settings / keys)
#   -Force          assume "yes" to every prompt (non-interactive)
$RemoveSkills = $args -contains "-RemoveSkills"
$RemoveEnv    = $args -contains "-RemoveEnv"
$Force        = $args -contains "-Force"

Write-Host ""
Write-Host "  DAITA - Uninstaller" -ForegroundColor Cyan
Write-Host "  Removing what the installer added outside the DAITA folder." -ForegroundColor Cyan
Write-Host ""

function Confirm-Step($message, $defaultYes = $true) {
    if ($Force) { return $true }
    if (-not [Environment]::UserInteractive) { return $defaultYes }
    $hint = if ($defaultYes) { "[Y/n]" } else { "[y/N]" }
    $answer = Read-Host "  $message $hint"
    if (-not $answer) { return $defaultYes }
    return $answer.Trim().ToLower().StartsWith("y")
}

# 1. Stop DAITA - free both ports so nothing is holding files open.
Write-Host "  [..] Stopping DAITA (freeing ports 7766 / 7777)..."
foreach ($port in @(7777, 7766)) {
    $lines = netstat -ano | Select-String ":$port\s" | Select-String "LISTENING"
    foreach ($line in $lines) {
        $procId = ($line.ToString() -split '\s+')[-1]
        if ($procId -match '^\d+$') {
            try { Stop-Process -Id ([int]$procId) -Force -ErrorAction Stop } catch {}
        }
    }
}
Write-Host "  [OK] DAITA stopped."

# 2. Remove the desktop shortcut (created outside the folder).
$shortcut = Join-Path ([Environment]::GetFolderPath('Desktop')) "DAITA.lnk"
if (Test-Path $shortcut) {
    Remove-Item -Force -Confirm:$false $shortcut
    Write-Host "  [OK] Removed desktop shortcut: DAITA"
} else {
    Write-Host "  [--] No desktop shortcut found (nothing to remove)."
}

# 3. Remove the generated launchers + runtime log (regenerated by the installer).
foreach ($f in @("start_daita.bat", "start_daita.vbs", "stop_daita.bat", "bridge.log")) {
    $p = Join-Path $root $f
    if (Test-Path $p) {
        Remove-Item -Force -Confirm:$false $p
        Write-Host "  [OK] Removed $f"
    }
}

# 4. .env - holds your saved settings (weather coords, port, any keys). Kept by
#    default so a reinstall keeps your config; removable on request.
$envFile = Join-Path $root ".env"
if (Test-Path $envFile) {
    $doEnv = $RemoveEnv -or (Confirm-Step "Delete your saved settings (.env)?" $false)
    if ($doEnv) {
        Remove-Item -Force -Confirm:$false $envFile
        Write-Host "  [OK] Removed .env"
    } else {
        Write-Host "  [--] Kept .env (your settings). Delete it by hand if you want."
    }
}

# 5. Bundled DAITA-core skills - shared with the rest of your Claude setup, so
#    they are KEPT by default. Only unmodified copies DAITA placed are removed,
#    and only if you opt in. Anything you edited or owned is always left alone.
$skillRemover = Join-Path $root "dashboard\uninstall_skills.py"
if (Test-Path $skillRemover) {
    $doSkills = $RemoveSkills -or (Confirm-Step "Also remove the bundled DAITA-core skills it installed?" $false)
    if ($doSkills) {
        $python = $null
        foreach ($cmd in @("python", "python3", "py")) {
            if (Get-Command $cmd -ErrorAction SilentlyContinue) { $python = $cmd; break }
        }
        if ($python) {
            Write-Host "  [..] Removing bundled skills (unmodified copies only)..."
            & $python $skillRemover
            Write-Host "  [OK] Skill removal pass complete (see list above)."
        } else {
            Write-Host "  [!!] Python not found - skipping skill removal." -ForegroundColor Yellow
            Write-Host "       Run later: python dashboard\uninstall_skills.py"
        }
    } else {
        Write-Host "  [--] Kept the bundled skills (used across your Claude setup)."
        Write-Host "       Remove later: python dashboard\uninstall_skills.py"
    }
}

# 6. Things we deliberately DO NOT touch.
Write-Host ""
Write-Host "  Left in place on purpose:" -ForegroundColor DarkGray
Write-Host "    - psutil (a shared Python package; other tools may use it)." -ForegroundColor DarkGray
Write-Host "      Remove it yourself with:  pip uninstall psutil" -ForegroundColor DarkGray
Write-Host "    - Your AI provider CLI (claude / codex / ...) - DAITA did not install it." -ForegroundColor DarkGray

# 7. Final step: the folder itself. The uninstaller is running from inside it,
#    so it cannot delete itself reliably - hand that last move to the user.
Write-Host ""
Write-Host "  Done. DAITA is uninstalled." -ForegroundColor Green
Write-Host "  The only thing left is this folder. Once this window is closed you"
Write-Host "  can safely delete it:"
Write-Host "    $root" -ForegroundColor Cyan
Write-Host ""
