#!/usr/bin/env python3
"""
DAITA — UI sound generator
-------------------------
Synthesizes the dashboard's seven UI sounds from pure math (sine partials +
exponential envelopes). Every sample is generated by this script — nothing
is recorded or derived from any existing audio, so the output is original
work with zero licensing baggage.

Run from anywhere:  python tools/make_sounds.py
Writes 16-bit 44.1 kHz mono WAVs to dashboard/sounds/.
"""

import math
import struct
import wave
from pathlib import Path

SR = 44100
OUT = Path(__file__).resolve().parent.parent / "dashboard" / "sounds"


def render(duration, voices, curve=3.5):
    """Sum sine voices over `duration` seconds.

    Each voice: (f_start, f_end, amp, t_on, t_off, decay)
      f sweeps exponentially f_start→f_end across the voice's window;
      amp envelope = fast attack, exponential decay shaped by `decay`.
    """
    n = int(SR * duration)
    buf = [0.0] * n
    for f0, f1, amp, t_on, t_off, decay in voices:
        i0, i1 = int(t_on * SR), min(n, int(t_off * SR))
        span = max(1, i1 - i0)
        phase = 0.0
        for i in range(i0, i1):
            x = (i - i0) / span                      # 0..1 within the voice
            f = f0 * (f1 / f0) ** x if f0 > 0 else 0
            phase += 2 * math.pi * f / SR
            env = min(1.0, x * 28.0) * math.exp(-decay * x)
            buf[i] += amp * env * math.sin(phase)
    # gentle master fade-out to kill clicks, then soft-clip
    fade = int(0.012 * SR)
    for i in range(max(0, n - fade), n):
        buf[i] *= (n - i) / fade
    return [math.tanh(s * curve) / math.tanh(curve) for s in buf]


def save(name, samples):
    OUT.mkdir(parents=True, exist_ok=True)
    path = OUT / f"{name}.wav"
    with wave.open(str(path), "wb") as w:
        w.setnchannels(1)
        w.setsampwidth(2)
        w.setframerate(SR)
        w.writeframes(b"".join(
            struct.pack("<h", int(max(-1, min(1, s)) * 32000)) for s in samples))
    print(f"  {path.name:16s} {len(samples)/SR:5.2f}s")


# ── The palette ──────────────────────────────────────────────
# Tuned around A=440 pentatonic-ish intervals so everything is consonant.

def main():
    print("Rendering DAITA UI sounds:")

    # confirm — crisp two-note rising blip (button presses; subtle)
    save("confirm", render(0.16, [
        (880, 880, 0.55, 0.00, 0.07, 6),
        (1318, 1318, 0.55, 0.06, 0.16, 6),
        (2636, 2636, 0.10, 0.06, 0.16, 8),     # sparkle partial
    ]))

    # engage — confident upward sweep with a shimmer tail (panel changes)
    save("engage", render(0.30, [
        (392, 1046, 0.60, 0.00, 0.22, 3.5),
        (784, 2093, 0.18, 0.00, 0.22, 4.5),
        (1568, 1568, 0.14, 0.20, 0.30, 7),
    ]))

    # transmit — three quick ascending pips (message sent)
    save("transmit", render(0.22, [
        (988, 988, 0.5, 0.00, 0.06, 8),
        (1318, 1318, 0.5, 0.07, 0.13, 8),
        (1760, 1760, 0.5, 0.14, 0.22, 8),
    ]))

    # receive — soft descending pair (reply arrived; easy on the ear)
    save("receive", render(0.26, [
        (1568, 1568, 0.45, 0.00, 0.11, 5),
        (1046, 1046, 0.50, 0.10, 0.26, 5),
        (523, 523, 0.12, 0.10, 0.26, 4),       # warm under-octave
    ]))

    # processing — airy double pulse on one tone (working…)
    save("processing", render(0.24, [
        (659, 659, 0.40, 0.00, 0.10, 6),
        (659, 659, 0.40, 0.12, 0.24, 6),
        (1318, 1318, 0.08, 0.00, 0.24, 6),
    ]))

    # error — low descending minor pair, slightly rough (something failed)
    save("error", render(0.34, [
        (440, 415, 0.55, 0.00, 0.14, 4),
        (311, 294, 0.60, 0.13, 0.34, 4),
        (622, 588, 0.15, 0.13, 0.34, 5),
    ]))

    # doorbell — pleasant two-chime ding-dong with long decay (notification)
    save("doorbell", render(0.70, [
        (1318, 1318, 0.50, 0.00, 0.45, 3),
        (2636, 2636, 0.10, 0.00, 0.45, 5),
        (988, 988, 0.50, 0.18, 0.70, 2.5),
        (1976, 1976, 0.10, 0.18, 0.70, 4.5),
    ]))

    print("Done.")


if __name__ == "__main__":
    main()
